function [weather, provenance] = importFile(path, location)
%IMPORTFILE Import CSV or Excel weather data into the canonical schema.

t = readtable(path);
t.Properties.VariableNames = lower(string(t.Properties.VariableNames));

% Supported aliases
aliases = struct( ...
    "time",  "timestamp", ...
    "t2m",   "temperature", ...
    "ws10m", "wind_speed", ...
    "rh",    "relative_humidity", ...
    "sp",    "pressure", ...
    "long",  "longitude");

fields = fieldnames(aliases);

for k = 1:numel(fields)
    oldName = string(fields{k});
    newName = string(aliases.(fields{k}));

    if ismember(oldName, t.Properties.VariableNames) && ...
            ~ismember(newName, t.Properties.VariableNames)
        t.Properties.VariableNames( ...
            t.Properties.VariableNames == oldName) = newName;
    end
end

% Required irradiance columns
required = ["timestamp", "ghi", "dhi", "dni"];

assert( ...
    all(ismember(required, t.Properties.VariableNames)), ...
    "SolarTilt:Schema", ...
    "Required columns are: timestamp, ghi, dhi, dni.");

% Parse timestamps
if ~isdatetime(t.timestamp)
    t.timestamp = parseTimestamps(t.timestamp);
elseif isempty(t.timestamp.TimeZone)
    t.timestamp.TimeZone = "UTC";
end

% Retain supported canonical columns
supported = [ ...
    "timestamp", ...
    "latitude", ...
    "longitude", ...
    "ghi", ...
    "dni", ...
    "dhi", ...
    "temperature", ...
    "wind_speed", ...
    "pressure", ...
    "relative_humidity", ...
    "source", ...
    "quality_flag"];

keep = intersect( ...
    supported, ...
    string(t.Properties.VariableNames), ...
    "stable");

weather = t(:, keep);
numberOfRows = height(weather);

% Add coordinates from configuration when absent
if ~ismember("latitude", string(weather.Properties.VariableNames))
    weather.latitude = repmat(location.latitude, numberOfRows, 1);
end

if ~ismember("longitude", string(weather.Properties.VariableNames))
    weather.longitude = repmat(location.longitude, numberOfRows, 1);
end

% Ensure canonical column order
canonicalOrder = intersect( ...
    supported, ...
    string(weather.Properties.VariableNames), ...
    "stable");

weather = weather(:, canonicalOrder);
weather = sortrows(weather, "timestamp");

% Record import provenance
provenance = struct( ...
    "sourceType",   'file', ...
    "sourceUri",    string(path), ...
    "dataset",      "user-supplied", ...
    "retrievedAt",  datetime("now", "TimeZone", "UTC"), ...
    "locationName", string(location.name));

end


function time = parseTimestamps(values)
%PARSETIMESTAMPS Parse supported timestamp representations.

textValues = string(values);

formats = [ ...
    "yyyy-MM-dd'T'HH:mm:ss'Z'", ...
    "yyyy-MM-dd'T'HH:mm:ssXXX", ...
    "yyyy-MM-dd HH:mm:ss", ...
    "yyyyMMdd:HHmm"];

for k = 1:numel(formats)
    try
        candidate = datetime( ...
            textValues, ...
            "InputFormat", formats(k), ...
            "TimeZone", "UTC");

        if all(~isnat(candidate))
            time = candidate;
            return
        end
    catch
        % Try the next documented format.
    end
end

error( ...
    "SolarTilt:TimestampFormat", ...
    "Unable to parse timestamps. Supported formats include ISO 8601 and yyyyMMdd:HHmm.");

end